// src/content/app.jsx
import { h, render } from "preact";
import { Header } from "./components/header.jsx";
import { MainContent } from "./components/mainContent.jsx";
import { Footer } from "./components/footer.jsx";
import { buildExampleDashboardData } from "../mockDashboardData.js";

window.replaceHeader = function replaceHeader(data = {}) {
	const isMockData = Boolean(window.__IDU_MOCK_DATA);
	if (window.location.pathname === "/users/sign_in" && !isMockData) return false;
	if (document.getElementById("idu-header-root")) return true;
	const oldHeader = document.querySelector("#top");
	if (!oldHeader) return false;
	const semesterScope = data.semesterScope || null;
	const searchElement = window.location.pathname === "/"
		? document.querySelector("#unique-id26")
		: null;
	searchElement?.remove();
	let accountHref
	if (document.querySelector("#account")) {
		accountHref = document.querySelector("#account").children[0].href;
	} else {
		accountHref = "/";
	}
	const mountPoint = document.createElement("div");
	mountPoint.id = "idu-header-root";
	oldHeader.replaceWith(mountPoint);
	if (window.location.pathname !== "/users/sign_in" || isMockData) {
		render(
			<Header
				accountHref={accountHref}
				messagesHref={data.messagesUrl || ''}
				semesterScope={semesterScope}
				searchElement={searchElement}
				isMockData={isMockData}
			/>,
			mountPoint
		);
	}

	return true;
};

window.renderIduMockDashboard = function renderIduMockDashboard() {
	const data = buildExampleDashboardData();
	window.__IDU_MOCK_DATA = data;

	// The real sign-in page has a different structure from the dashboard shell
	// previously generated by the proxy. Build that shell locally before asking
	// the Preact replacement functions to mount into it.
	const top = document.createElement("div");
	top.id = "top";
	const content = document.createElement("div");
	content.id = "content";
	const footer = document.createElement("footer");
	footer.id = "footer";
	document.body.replaceChildren(top, content, footer);
	document.body.className = "";
	document.body.setAttribute("path", "/");
	document.title = "IDU Demo";

	const headerLoaded = window.replaceHeader(data);
	const contentLoaded = window.replaceMainContent(data);
	const footerLoaded = window.replaceFooter();
	window.hideVisualLoader?.();
	window.scrollTo(0, 0);

	console.info("[IDU2] Local Apple review dashboard loaded", {
		headerLoaded,
		contentLoaded,
		footerLoaded,
	});
	return headerLoaded && contentLoaded;
};

window.replaceMainContent = function replaceMainContent(data) {
	const oldMainContent = document.getElementById("content");
	if (!oldMainContent) return false;

	oldMainContent.innerHTML = "";
	render(<MainContent data={data}/>, oldMainContent);

	return true;
};

window.replaceFooter = function replaceFooter() {
	const oldFooter = document.getElementById("footer");
	const mountPoint = document.createElement("footer");
	mountPoint.id = "footer";

	if (oldFooter) {
		oldFooter.replaceWith(mountPoint);
	} else {
		document.body.append(mountPoint);
	}

	if (window.location.pathname === "/users/sign_in") {
		render(<Footer/>, mountPoint);
	}

	render(<Footer/>, mountPoint);
	return true;
};
